### ISSUE TITLE
Tracked mesh becomes bad since 2k steps

### ISSUE THREAD

**Issue by essen900718** [ShenhanQian/VHAP#10]
Dear authors,

Thanks for your work!  
We've been encountered a problem with the tracker specifically the tracked mesh just becomes terribly morphed after 2k steps. 
Here's the steps we did for capturing our own dataset:
1. set up 7 cameras, do the calibration, and capturing concurrently
2. processing step 1 without background and without color correction
    - we have checked the alpha_maps and there're no problems
3. processing step 2 - tracking, and the problem occurs

I may append some images for illustration.

**--- Step 999 --- still okay** 
![frame_00000_999_lmk_init_all](https://github.com/user-attachments/assets/9dd29ec0-812e-48a3-9c61-03c4118b177e)

**--- Step 1499 --- also okay**
![frame_00000_1499_rgb_init_texture](https://github.com/user-attachments/assets/f65722e0-7667-4efe-b110-d0b3b0ad09a1)

**--- Step 1999 --- already morphed**
![frame_00000_1999_rgb_init_all](https://github.com/user-attachments/assets/d139f97f-14f4-4f31-ad3e-b4303570ce92)

**--- afterwards --- continually worse**
![frame_00000_2499_rgb_init_offset](https://github.com/user-attachments/assets/d904c0b9-a966-435f-9fc5-11bcc4f92254)

We hope to receive your comments and instructions to get through this problem! Thank you so much.

Best regards,
Isadora

**Comment by ShenhanQian** [comment]
Hi Isadora, thanks for sharing your results. 

The main problem is probably a too-high regularization on the texture map. The default value is 1e5 for NeRSemble.  Since you only have 7 views, about half of 16 for NeRSemble, you may try a lower value by passing `--w.reg_tex_tv 3e4` or 1e4.

**Comment by essen900718** [comment]
Hi Shenhan, 
Thanks a lot for your reply, it has helped me a lot!
