### ISSUE TITLE
Where to find FLAME_texture.npz

### ISSUE THREAD

**Issue by VincentHu19** [ShenhanQian/VHAP#13]
When I want to use the pca texture space as the base texture map, instead of the painted texture map, I find no such file 'asset/flame/FLAME_texture.npz'. Could you please release this 'FLAME_texture.npz'?

**Comment by ShenhanQian** [comment]
This file can be downloaded from FLAME's official website: https://flame.is.tue.mpg.de/download.php 
"FLAME texture space (for non-commercial use only)"

**Comment by VincentHu19** [comment]
Got it! Thanks a lot!
