### ISSUE TITLE
Question about Color Calibration Process Between Multiple Cameras

### ISSUE THREAD

**Issue by Jp-17** [ShenhanQian/VHAP#16]
Hello, I have two questions regarding the color calibration process between different cameras:

1. Could you please explain the process of obtaining the color calibration data (presumably an affine color transformation matrix) between different cameras during data collection?

2. When using a color checker to calibrate the white balancing factors and gamma parameters for each camera:
   - Do all cameras need to capture the color checker in the same frame at the exact same moment?
   - If simultaneous capture across all cameras isn't possible, would that affect the calibration results?

Thank you in advance for any insights!

**Comment by ShenhanQian** [comment]
Hi,

Q2. In my opinion, it's not a big problem if the capturing does not happen at exactly the same moment as long as the lighting condition is consistent.

Q1. Besides what was written in the NeRSemble paper, I think @tobias-kirschstein and @SimonGiebenhain can share more details if you have specific questions :D

**Comment by Jp-17** [comment]
Thank you for your reply. 

Yeah, I should go to the NeRSemble paper project for more details.
