### ISSUE TITLE
How to train GaussianAvatars using the output from this repo for custom mono videos?

### ISSUE THREAD

**Issue by longyangqi** [ShenhanQian/VHAP#17]
Very thanks for the released preprocessing code!
I want to train GaussianAvatars using custom mono videos.
Now, I can get the result of tracked_flame_params using this repo. But I do not know how to use this to train GaussianAvatars.
Do I need extra colmap for camera params ? Or I can directly use the camera params from tracked flames?
Could you provide some guidances/examples for this?
Thanks!

**Comment by ShenhanQian** [comment]
Hi, the exported result of VHAP can be directly used for GaussianAavatars as long as you follow all the procedures [here](https://github.com/ShenhanQian/VHAP/blob/main/doc/monocular.md).

**Comment by longyangqi** [comment]
> Hi, the exported result of VHAP can be directly used for GaussianAavatars as long as you follow all the procedures [here](https://github.com/ShenhanQian/VHAP/blob/main/doc/monocular.md).

Thanks for the rapid reply, my fault, I left out the `Export tracking results into a NeRF-style dataset` part.
I will close the issue.
