### ISSUE TITLE
Could this repo process multiview portrait images which are not consecutive frames of a video?

### ISSUE THREAD

**Issue by hh0525** [ShenhanQian/VHAP#2]
Thanks for release! Could this repo process multiview portrait images which are not consecutive frames of a video?

**Comment by ShenhanQian** [comment]
Non-consecutive frames are not directly supported but should not be hard to modify.

1. We have [temporal smoothness losses](https://github.com/ShenhanQian/VHAP/blob/e1f13769b2b3799703fb15fbef6b05c36616a943/vhap/config/base.py#L174-L183), which assume consecutive frames. You can set their weights to 0.

1. Our current tracking pipeline contains the following stages:
https://github.com/ShenhanQian/VHAP/blob/e1f13769b2b3799703fb15fbef6b05c36616a943/vhap/model/tracker.py#L1473-L1488
We optimize for [2.5k](https://github.com/ShenhanQian/VHAP/blob/e1f13769b2b3799703fb15fbef6b05c36616a943/vhap/config/base.py#L225-L273) steps on the first frames, and only [50 steps](https://github.com/ShenhanQian/VHAP/blob/e1f13769b2b3799703fb15fbef6b05c36616a943/vhap/config/base.py#L281) on each following frames assuming that their differences are small.
But for your non-consecutive case, you may want to run more steps for each new frame. Also, if the changes are too large, the photometric optimization may stuck in a local optima. You may need to [optimize only with landmarks](https://github.com/ShenhanQian/VHAP/blob/e1f13769b2b3799703fb15fbef6b05c36616a943/vhap/model/tracker.py#L1487) for a few steps to make FLAME roughly aligned to the new frame before enabling [photometric optimization](https://github.com/ShenhanQian/VHAP/blob/e1f13769b2b3799703fb15fbef6b05c36616a943/vhap/model/tracker.py#L1485).

To ease development, you can first use `--exp.no_photometric` to optimize only with landmarks. Once done, you can move to photometric optimization.

**Comment by longyangqi** [comment]
I have a question about tracking from monocular video.
As the pipeline optimizes for 2.5k steps on the first frame to initialize the shape and appearance parameters, do we need to the first frame be a frontal view?

**Comment by longyangqi** [comment]
> Ideally yes, otherwise the texture map of the hidden region will not be great. Meanwhile, later optimization can fix this problem gradually.

If the video does not start with a front view, how to process would be better?
1. Clip the video till a front view to be the first frame.
2. Put a front view to be the first frame, then I think we need to set the smooth loss between first and second frame to be 0, and cannot initial the second frame pose by the first frame. can we achieve this? Could you provide some guidance on this?
Very Thanks!

**Comment by ShenhanQian** [comment]
Before you break the continuity between the first and second frames, here are a few aspects that you need to consider:

1. We assume that the initial FLAME parameters are far from the ground truth. Therefore, we reserve hundreds of iterations for optimization on the first frame. For every following frame, we use the optimized parameters of the previous frame for initialization and optimize for only 50 iterations, assuming the difference is small.

2. As you mentioned, we also apply the temporal smoothness term as regularization.

It can be tricky if you put a chosen front-view image as the first frame, which breaks the continuity assumption above. I would recommend starting with the original video and seeing how bad the results are and whether the later-on optimization can gradually fix it.
