### ISSUE TITLE
the question of render.py

### ISSUE THREAD

**Issue by zhang-zrq** [ShenhanQian/VHAP#20]
Hi，hanqian

**sorry, I mistakenly looked at the wrong project when submitting the issue. In fact, I intended to submit this issue under the `GaussianAvatar` project.**

The `GaussianAvatars` project is an outstanding piece of work that has been immensely helpful to me.

However, I encountered an issue while running the project. When I executed the following command, I was unable to obtain the rendering results:

```
SUBJECT=253

python render.py \
-m output/UNION10EMOEXP_${SUBJECT}_eval_600k \
--skip_train --skip_val \
--select_camera_id 8
```

The error message is as follows:
![image-20241123194321487](https://github.com/user-attachments/assets/54b071a5-a9fe-4c39-b810-dc42a7b660e1)

Analysis indicates that the absence of rendered images in the target folder is the reason why ffmpeg cannot compile them into a .mp4 file.

During my debugging , I found that the `scene.getTestCameras()` method in `render.py` pass an empty `CameraDataset` object to the following line of code:

```
if not skip_test:
	render_set(dataset, "test", scene.loaded_iter, scene.getTestCameras(), gaussians, pipeline, background, render_mesh)
```

by the way, since I am using a dataset of type `DynamicNerf`, so `readDynamicNerfInfo` is called to load the data. However, [[the code](https://github.com/ShenhanQian/GaussianAvatars/blob/b799256675aea75ffd0d3aa8c69f774853e3d618/scene/dataset_readers.py#L332-L338)] merge `test_cam_infos` into `train_cam_infos` and then clear `test_cam_infos`, which results in `scene.getTestCameras()` being an empty object in `render.py`. When I comment out [[the code](https://github.com/ShenhanQian/GaussianAvatars/blob/b799256675aea75ffd0d3aa8c69f774853e3d618/scene/dataset_readers.py#L332-L338)] (although this is not a reasonable operation), the program can produce the correct results

Finally,Is it possible for me to pass a `test` parameter to `readDynamicNerfInfo()` as shown below? I would like to ask if doing so would have any impact on other parts of the project's functionality. Alternatively, are there any other methods available? 

```
def readDynamicNerfInfo(path, white_background, eval,test,extension=".png", target_path=""):
	'''···'''
	# if target_path != "" or not eval:
    if target_path != "" or not (eval or test):
    '''··· '''
```

Looking forward to your response.

**Comment by ShenhanQian** [comment]
Can you remove this issue and re-post GaussianAvatars?

**Comment by zhang-zrq** [comment]
When I found out that I submitted an error and wanted to delete it, but I don't have the permission to delete it
[The only account that can delete issues in a repository owned by a personal account is that account.](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/deleting-an-issue#:~:text=The%20only%20account%20that%20can%20delete%20issues%20in%20a%20repository%20owned%20by%20a%20personal%20account%20is%20that%20account.)

Could you please delete it，and then I will re-post it in the GaussianAvatars repo

Thank you very much.

**Comment by ShenhanQian** [comment]
Sure, deleting now
