### ISSUE TITLE
How to estimate flame parameters in real-time based on input images?

### ISSUE THREAD

**Issue by ZCB-endeavor** [ShenhanQian/VHAP#21]
Hi, thanks for your great work!

I want to achieve the function of capturing face image through a camera and driving GaussianAvatars model in real-time.

I noticed that VHAP has obtained high-precision flame parameters through facial tracking and optimization. Can VHAP estimate flame parameters in real-time?

I'm looking forward to your reply.

**Comment by ShenhanQian** [comment]
Hi, the accurate geometry comes from differential rasterization (nvdiffrast), which currently only runs on first-order optimizers in Pytorch such as Adam, which may not be sufficient for real-time tracking without special design.

**Comment by ZCB-endeavor** [comment]
Thank you for your answer, I will continue to try other options to solve this problem.

**Comment by AmoreSG** [comment]
Sorry to bother you, ZCB-endeavor.
I’d like to achieve the same functionality. Have you already implemented it? What methods did you use, or do you have any suggestions?

**Comment by ZCB-endeavor** [comment]
You can use [DECA](https://github.com/yfeng95/DECA) or [SMIRK](https://github.com/georgeretsi/smirk) for real-time estimation of the flame parameters. SMIRK takes some time to initialize the model, but it can basically reach real-time when reasoning about the flame parameters. I think this is a good alternative for real-time parameter inference. However, it should be noted that the model used in these two projects is FLAME 2020, so GaussianAvatars should also use FLAME 2020 when training.
