### ISSUE TITLE
AttributeError: 'MaskFromFLAME' object has no attribute 'cfg_data'

### ISSUE THREAD

**Issue by why986** [ShenhanQian/VHAP#24]
Hi author(s), 
Thank you for your amazing work on this repository! I truly appreciate the effort you’ve put into it.

While exporting the dataset as a NeRF dataset, I encountered a small issue. Below is the command I ran:
```shell
SUBJECT="074"
SEQUENCE="EMO-1"
TRACK_OUTPUT_FOLDER="output/nersemble/${SUBJECT}_${SEQUENCE}_v16_DS4_wBg_staticOffset"
EXPORT_OUTPUT_FOLDER="export/nersemble/${SUBJECT}_${SEQUENCE}_v16_DS4_whiteBg_staticOffset_maskBelowLine"

python vhap/export_as_nerf_dataset.py \
--src_folder ${TRACK_OUTPUT_FOLDER} \
--tgt_folder ${EXPORT_OUTPUT_FOLDER} 
```
without specifying the `background-color`. An error occurred [here](https://github.com/ShenhanQian/VHAP/blob/419eb4cc82cc093fe3447a39b9ac3b8e3b4dc91f/vhap/export_as_nerf_dataset.py#L353).

It seems like a minor revision to handle this edge case could resolve the issue. I hope this helps improve the robustness of the code.

**Comment by ShenhanQian** [comment]
Hi Haoyu, thanks for reporting the corner case! I have fixed it in the latest commit (https://github.com/ShenhanQian/VHAP/commit/7a7d241672a5b877ed8316b46ed740edb6fad01e)

**Comment by why986** [comment]
Hi Shenhan, thank you for addressing the issue so promptly. I really appreciate your work.
