### ISSUE TITLE
Unable to load detected landmarks: AssertionError: index is required when camera_id is not provided.

### ISSUE THREAD

**Issue by trThanhnguyen** [ShenhanQian/VHAP#3]
Hi, thanks for publishing your work.

I have obtained images, alpha_maps, landmarks and they're structured as suggested. 
However, during making the dataset in ```vhap/model/tracker.py``` - ```GlobalTracker```, I'm getting the assertion error in ```VideoDataset.get_property_path()```, called by ```VideoDataset.load_landmarks()``` in ```vhap/data/video_dataset.py```:
```
AssertionError: index is required when camera_id is not provided.
```
The definition of ```get_property_path```:
```
    def get_property_path(
        self,
        name,
        index: Optional[int] = None,
        timestep_id: Optional[str] = None,
        camera_id: Optional[str] = None,
    ): ...
```
and the only argument that got passed is the ```name```:
```
if self.cfg.landmark_source == "both": 
                npz_fa = np.load(self.get_property_path("landmark2d/face-alignment"))
```
This makes ```index=None``` and ```camera_id=None```, which causes the error.

Could you please give some further instruction how to get through this?

Many thanks.

**Comment by ShenhanQian** [comment]
Hi, which data are you using? Monocular or multiview? Our examples or your own ones?

**Comment by trThanhnguyen** [comment]
Hi, I'm using the NeRSemble dataset with multi-view videos. The error was encountered during step 2 - Align and track face.
Thanks.

**Comment by AbhinavUtkarsh** [comment]
I face the same issue

**Comment by ShenhanQian** [comment]
Thanks for reporting this problem. We have fixed it with the lastest commit.

**Comment by AbhinavUtkarsh** [comment]
It works now :D

**Comment by trThanhnguyen** [comment]
Thank you, it works now.

**Comment by trThanhnguyen** [comment]
solved
