### ISSUE TITLE
Questions about process custom datasets 

### ISSUE THREAD

**Issue by ZhengyuDiao** [ShenhanQian/VHAP#6]
Thanks for release the great work!
while I use this repo to process my custom dataset which contains multi-view videos and  camera calibrations. I rewrite the dataset codes and try to keep dataloader ouput in same format with nersemble_dataset.py, however, the alignment result below looks strange. the photo loss is inf in process. 
Are there any other things to pay attention to when processing custom dataset?
![截图 2024-09-13 21-14-46](https://github.com/user-attachments/assets/46fe12fb-e944-46cb-b9f5-c65a2a945385)

**Comment by ZhengyuDiao** [comment]
> Hi, thanks for sharing your result! How many views do you have in your multi-view setting?

I use 3 views

**Comment by ShenhanQian** [comment]
I see. Since you have fewer views than NeRSemble (16 views), you may need to weaken the regularization on the texture map by `--w.reg_tex_tv 1e4` or 3e4. The texture map after optimization should be a little blurry than the GT image but much sharper than what you have now.

**Comment by ZhengyuDiao** [comment]
Thanks!

**Comment by ShenhanQian** [comment]
Which value for `w.reg_tex_tv` works best for you?  Do you need to do other adjustments to make it work?
