### ISSUE TITLE
Processing custom datasets

### ISSUE THREAD

**Issue by vipinsdk** [ShenhanQian/VHAP#7]
Hello Shenhan, 

Thanks for sharing the preprocessing code for Gaussian Avatars paper. I want to train the Gaussian Avatars model with my own custom dataset. I am capturing a multi-view dataset consisting of 6 cameras and the I have done the camera calibration and have the camera parameters in OPENCV "yml" file format consisting all the parameters from 6 cameras in two files, one for intrinsics and other one for extrinsics. I want to use this recorded videos and preprocess it using this repository. 
I want to know how I should structure my data to run this pipeline. I saw the format described for nerRSemble but I still have few questions:

1. What is the exact input to this pipeline, is it just videos and their corresponding camera parameters? What else do I need to provide as input for this pipeline?
2. Do I need to also provide background images for each of the camera?
3. This code will generate the facial landmarks based on the dataset right?

Finally, I already have access to NeRSermble dataset from Gaussian Avatars paper, does the dataset here differ from that paper. 

Thanks and Regards
Vippin

**Comment by ShenhanQian** [comment]
Hi Vippin, thanks for your questions.

1. Basically, videos and camera parameters are all you need. NeRSemble dataset also provides color correction data for each view. But you can ignore it if you don't have this data.
2. Preferrably, providing background images for each camera allows you to use [BackGroundMattingV2](https://github.com/ShenhanQian/BackgroundMattingV2). It produces better matting results than [RobustVideoMatting](https://github.com/PeterL1n/RobustVideoMatting), which does not require background images. This only relates to [preprocessing of the data](https://github.com/ShenhanQian/VHAP/blob/main/doc/nersemble.md#1-preprocess).
3. Yes, the landmarks will be generated on the first run and stored with the preprocessed data for re-use.

Finally, videos in NeRSemble undergo a mild compression before release. The difference can be ignored.

**Comment by vipinsdk** [comment]
Hello Shenhan,

Thanks for the reply. I have managed to do get my custom dataset to the required format and now I want to train the model but I am facing issues with NVDiffRast 

```
[F919 03:43:17.854078983 glutil.cpp:338] eglInitialize() failed
Aborted (core dumped)
```

I am trying to run the code on a cluster and it does not have display. I saw some fixes online but none of them work and eventually I get this error. 

For now: I thought of a workaround of disabling the `use_opengl` flag to False but I am not sure if it will make any difference or if it is even recommended to do so. 

Please let me know if there is a fix for this issue. 

Thanks and Regards,
Vippin

**Comment by ShenhanQian** [comment]
Setting `use_opengl` to false will switch nvdiffrast to its CUDA backend. It works similarly but has a stricter limitation on the resolution:
> The CUDA rasterizer does not support output resolutions greater than 2048×2048, and both dimensions must be multiples of 8. 

Given that the OpenGL backend is more flexible, I would still recommend to fix the environment. From my personal experiences of deploying this repo on different clusters, it should usually work if you can let `glxgears` run smoothly. For a machine without monitor, you can still do this with X11 forwarding.

**Comment by vipinsdk** [comment]
Hello Shenhan, 

Thanks for the reply. I was successful in making the code run in server without an display by setting `export EGL_PLATFORM="surfaceless"` but the code crashes with the following error:

```
Traceback (most recent call last):
  File "/home/jeetmal/VHAP/vhap/track_nersemble.py", line 21, in <module>
    tracker.optimize()
  File "/home/jeetmal/VHAP/vhap/model/tracker.py", line 1479, in optimize
    self.optimize_stage('rgb_init_texture', sample)
  File "/home/jeetmal/VHAP/vhap/model/tracker.py", line 1515, in optimize_stage
    self.optimize_iter(sample, optimizer, stage)
  File "/home/jeetmal/VHAP/vhap/model/tracker.py", line 1543, in optimize_iter
    ) = self.compute_energy(
  File "/home/jeetmal/VHAP/vhap/model/tracker.py", line 825, in compute_energy
    rast_dict = self.rasterize_flame(
  File "/home/jeetmal/VHAP/vhap/model/tracker.py", line 361, in rasterize_flame
    rast_dict = self.render.rasterize(verts, faces, RT, K, image_size, False, train_mode)
  File "/home/jeetmal/VHAP/vhap/util/render_nvdiffrast.py", line 224, in rasterize
    rast_out, rast_out_db = self.rasterize_fragments(verts_clip, tri, image_size, use_cache, require_grad)
  File "/home/jeetmal/VHAP/vhap/util/render_nvdiffrast.py", line 247, in rasterize_fragments
    rast_out, rast_out_db = dr.rasterize(self.glctx, verts_clip, tri, image_size)
  File "/root/miniconda3/envs/VHAP/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/root/miniconda3/envs/VHAP/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/VHAP/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 246, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]
```
I am not sure, why this error occurs. I know that this NVDiffRast error but I have not changed the code so I assume it would run without errors. Have you also faced this error and can you let me know how this can be solved. 

I am using the same package version as mentioned in the README.md
Following are the version of CUDA:
nvidia-smi - 12.6
nvcc - 12.1 (inside the conda env)

Thanks in advance

Regards,
Vippin

**Comment by ShenhanQian** [comment]
Hi Vippin, sorry that I had no experience with this error. You could install official nvdiffast in a separate environment and see if you can run their examples successfully on your remote machine.

**Comment by vipinsdk** [comment]
Hello Shenhan, 

Thanks for your reply. 
I was unable to solve this issue regarding opengl both on my local system and on the server ( headless) mode. 
Currently I am trying to run the code with a cuda rasterizer and for that I have some questions:

1. Why do we run on the down sampled images (4) instead of original images.
2. Does the number of cameras and the training parameters (all of them) need to be matched and adjusted depending on the number of cameras? ( I ran the code with the original image size of 1080 x 1920 because the down sampled image size is not divisible by 8 and hence not compatible with cuda rasterizer and the results are not good, the landmarks do not align with the face and also the face_alignment becomes stretched out or elongated and doesn't fit the face at all) 
3. I am using 6 cameras but the code shows output for only 3 cameras, I guess but I am not sure? 

Finally, does the video sequence need to contain only face and shoulders or it can be an entire person standing? 

Thanks in advance 

With Regards
Vippin

**Comment by ShenhanQian** [comment]
Hi Vippin, for you questions

1. Downsampling is just for efficiency. Higher than 512x512 will only make tracking slow without much improvement in quality because the number of vertices of FLAME is limited.
2. Yes. When the number of cameras if fewer, you may try lower the regularization on the texture map by `--w.reg_tex_tv 1e4` or `--w.reg_tex_tv 3e4`. If the neck is stretched unnatrually, you can try `--model.occluded neck_lower boundary` or either of `neck_lower` `boundary`.
3. That's no problem. We only visualize three to avoid the image being too large. You can visualize more by `--log.max_num_views 6`. For more configuration options, see [here](https://github.com/ShenhanQian/VHAP/tree/main/vhap/config).
4. There is no hard constraint in the pipeline to prevent you from capturing a larger scene. A major concern would be the accuracy of landmark detection. Feel free to share results if you have tried.

**Comment by vipinsdk** [comment]
Hello Shenhan,

Thanks for the reply.  I have few additional questions:
1. During video extraction we get alpha_maps, will the result get better if we use if for training as well. I saw the config with `use_alpha_map` set to False and not used
2. Are all the cameras in Nersemble dataset have same camera intrinsics, I saw only one camera matrix K loaded for all views. 
3.  Here is an example mesh and this is when i run the model on the original dimension without down_sampling, we can see the mesh is not proper. 
![image](https://github.com/user-attachments/assets/d2ca7055-836c-422c-807b-3119c963c71e)
4. The mesh develops a bump for hair when it is doing `rgb_init_offset`, why is this and can it avoided if we use the alpha_map during training, like here (red circle)
![image](https://github.com/user-attachments/assets/d586896f-ed92-43ff-935f-3fbf27df7136)

With Regards,
Vippin

**Comment by ShenhanQian** [comment]
Hi Vippin,

1. It depends on the affinity between the background and foreground color. We mask out the background for monocular videos but keep it for NeRSemble because the multiview observation in NeRSemble is sufficient.
2. Yes.
3. Is the result also bad with downsampling? Can you show the original visualization, "image_grid" in the output folder?
4. In this case, masking out the background may help. But it would be very helpful to check the color affinity if you can show the original visualization here.

**Comment by NikoBele1** [comment]
Hello, i would like to add a question to this topic.

Do i need to correct for distortion when i do camera parameter estimation for my dataset? I have a custom dataset with 8 view. I use colmap to compute the camera parameters. Can i now use VHAP on my images and parameters, or do i have to undistort my dataset?

**Comment by Jp-17** [comment]
I also try to use my own collected data for training. Regarding the process of handling camera parameters, I have the following questions:

1. I noticed that the nersemble dataset paper mentions obtaining camera parameters through chessboard calibration. If we obtain camera parameters through Colmap or RealityCapture, would it affect the accuracy of the camera parameters and consequently impact the VHAP processing results?

2. Can the camera parameters obtained from Colmap or RealityCapture be used directly in VHAP? We encountered some issues when using RealityCapture in practice and would like to seek your insights based on your experience:

2.1 We used 16 cameras for shooting and collection, then used RealityCapture to process single-frame images from 16 camera angles to reconstruct the model and export camera parameters. The intrinsic and extrinsic parameters of all 16 cameras are different (see attachment). I have already modified the camera parameter loading method in VHAP to support different camera intrinsics.

2.2 When I directly used the camera parameters obtained in 2.1 in VHAP, I first noticed that the facial landmarks obtained through FLAME were all clustered together (as shown in Figure 1). Suspecting that the camera extrinsic translation was too large, I then divided the camera extrinsic translation by 100 before analyzing it through VHAP, which improved the results (as shown in Figure 2). I'm not sure if you know why this is the case.

2.3 However, in Figure 2, comparing the relationship between the mesh in the second column and the person's position, as well as the facial landmark labeling in the last column, there still seem to be some issues. For example, the mesh alignment for views 8/9/10/14/15 is not very good. Are there any problems with the camera parameters for these views or in the entire processing that I haven't noticed?

2.4 Additionally, there's a minor issue: in the last column of landmarks in Figure 2, some views like rows 3/5 don't show the landmarks obtained by the STAR method. What could be causing this?

File 1:
[camera_params.json](https://github.com/user-attachments/files/17309658/camera_params.json)

Fig 1:
![image](https://github.com/user-attachments/assets/a5295f28-97fd-42d0-9a74-2bb81390c004)

Fig 2:
![frame_00028](https://github.com/user-attachments/assets/0a69ae0e-9f16-4e79-a6ee-fa32b9df20d1)

**Comment by ShenhanQian** [comment]
Thanks for pointing out the inconsistency! The correct answer is "world2camera in OpenCV convention", which is supported by [this function](https://github.com/ShenhanQian/VHAP/blob/d3c2e82209bf9f2c96a6fd06e2e052d08b56c4af/vhap/data/nersemble_dataset.py#L74-L115). I have also updated the [incorrect comment](https://github.com/ShenhanQian/GaussianAvatars/issues/9#issuecomment-1961014388).

You should use the translation of c2w to plot the pose. The way I memorize and verify it is
> Given the origin x=(0,0,0) in the camera space, the c2w matrix will transform x to its location in the world space,
> <div align="center"> <img width="463" alt="image" align="center" src="https://github.com/user-attachments/assets/cb902e00-3754-4965-a290-7cbdc7a2ed3e"></div>
> , which is exactly the translation in the c2w matrix. Same for the orientation.

**Comment by Jp-17** [comment]
Yeah, I mistake it, thanks for your patience!

**Comment by NikoBele1** [comment]
@ShenhanQian Sorry to bother you again, but i have another question which fits into your discussion here. When i visualize the nersemble camera params with https://github.com/tobias-kirschstein/dreifus the cameras are facing negative z axis and their translation vector is roughly scaled between -1 and 1. 
When i do a colmap reconstruction on my data, the cameras are facing in a different direction, and are scaled between ~ -5 and 5. Is it necessary to transform my extrinsic params (red in the image below), such that my cameras are in the same place as nersemble cameras (green below)? 

![colmap_visu](https://github.com/user-attachments/assets/1a7b594b-dbdf-46c5-a08e-ebadea31970e)

**Comment by ShenhanQian** [comment]
Hi Niko. The locations and orientations of the cameras depends on how they are arranged in the real world. They don't have to be the same as NeRSemble.

But you remind me of the scale problem when using camera extrinsic parameters from COLMAP instead of calibration. For NeRSemble, a camera at point (0, 0, 1) means a point one meter away from the origin. But for COLMAP, the space is up-to-scale.

Having camera locations up-to-scale is not a problem for NeRF/3DGS training before the learned radiance field are scaled along with the camera locations. However, it is a problem for FLAME fitting because FLAME vertices are measured in meters. Therefore, you may need to optimize for a scaling factor for FLAME to adapt to the scale of COLMAP results.

The dataloader for COLMAP results and scaling factor optimization are not implemented yet. You are welcomed to make a pull request.

**Comment by NikoBele1** [comment]
Thank you for the clarification. Regarding orientation:

> The locations and orientations of the cameras depends on how they are arranged in the real world. They don't have to be the same as NeRSemble.

I don't mean that my cameras have to be in the same position as NeRSemble cameras. I would like to know if the cameras have to face the same direction (negative z axis), because my cameras in colmap space face also negative z, but in opencv space they face negative y, as seen in my image. So my question is, do i need to rotate them to face negative z?

**Comment by NikoBele1** [comment]
i might have mixed up something, thanks for your responses

**Comment by Lxiangyue** [comment]
> Hello Shenhan,
> 
> Thanks for the reply. I have managed to do get my custom dataset to the required format and now I want to train the model but I am facing issues with NVDiffRast
> 
> ```
> [F919 03:43:17.854078983 glutil.cpp:338] eglInitialize() failed
> Aborted (core dumped)
> ```
> 
> I am trying to run the code on a cluster and it does not have display. I saw some fixes online but none of them work and eventually I get this error.
> 
> For now: I thought of a workaround of disabling the `use_opengl` flag to False but I am not sure if it will make any difference or if it is even recommended to do so.
> 
> Please let me know if there is a fix for this issue.
> 
> Thanks and Regards, Vippin

I fixed it simply with replacing dr.RasterizeGLContext with dr.RasterizeCudaContext in ShenhanQian/nvdiffrec and VHAP. And re-install these two repo.

**Comment by ShenhanQian** [comment]
Thanks for sharing your solution!

Given an upgrade of `nvdiffrast`, VHAP now runs entirely based on CUDA. Please pull the latest commit and upgrade `nvdiffrast` as instructed here:
https://github.com/ShenhanQian/VHAP/releases/tag/v0.0.2
